name: Build MAUI Android (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, revive-local-mock ]
jobs:
  build-android:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: dotnet --info
        run: dotnet --info
        shell: pwsh

      - name: Install MAUI Android workload
        run: |
          dotnet workload install maui-android --source https://api.nuget.org/v3/index.json
          dotnet workload restore
        shell: pwsh

      - name: Restore solution
        run: dotnet restore EcoVital.sln
        shell: pwsh

      - name: Build Debug (net8.0-android)
        run: dotnet build "EcoVital/EcoVital.csproj" -c Debug -f net8.0-android /p:SkipInvalidConfigurations=true
        shell: pwsh

      - name: Publish Debug APK
        run: dotnet publish "EcoVital/EcoVital.csproj" -c Debug -f net8.0-android /p:AndroidPackageFormat=apk /p:EmbedAssembliesIntoApk=true
        shell: pwsh

      - name: List APKs
        run: Get-ChildItem -Recurse -Filter *.apk | ForEach-Object { Write-Host $_.FullName }
        shell: pwsh

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: "**/*.apk"
